name: semantic_search
channels:
  - conda-forge
dependencies:
  - python=3.13
  - numpy>=2.0.0
  - pandas>=2.2.0
  - scikit-learn>=1.6.0
  - pyarrow>=18.0.0
  - pip:
      - datasets>=3.0.0
      - rank_bm25>=0.2.2
      - sentence-transformers>=3.0.1
      - faiss-cpu>=1.9.0